### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by kum-deepak** [fpozzobon/webstomp-obs#10]
Hi @fpozzobon,

I have been maintaining a fork of the original code at https://github.com/stomp-js/stomp-websocket and a layer on top using RxJS with support for Angular2+ at https://github.com/stomp-js/ng2-stompjs

I had realized that most ideal solution will involve creating 3 versions:

- One JS version (without RxJS), this can be close to the original API for easy migration path
- One JS version (With RxJS)
- One version with RxJS specialized for Angular2+

I was looking to break away from original code base and clean original API. Currently in the planning phase.

I have started realizing that your approach is quite nice and if we can collaborate, we can create and maintain a better product.

Let me know your thoughts!

**Comment by fpozzobon** [comment]
Hi @kum-deepak ,

Thank you for your feedback on my library, I really appreciate :)
About the js version without RxJS, I am not sure if this is really necessary... although I understand that it could be usefull for people not willing to use RxJS...
I guess ideally the libraries should depend to each other : 
Stomp (without RxJS) => RxJs Stomp => Ng RxJS Stomp

For that library, I wanted actually to make it modular so Stomp would be just a protocol like another that we could plug... but... erm... not sure the current architecture is right and I like to try keeping thing as simple as possible ;)

I would be glad to collaborate with you :)
Although at the moment I am a bit busy as I moved recently to Finland... but will do my best :p 

Please let me know how you would like to proceed 

Cheers ! :)

**Comment by kum-deepak** [comment]
Many thanks!

I will create a new project and add you as a collaborator. I know the code size is not going to be huge, so, I am ok to write most of the code. More than code, currently, i am looking for someone to discuss ideas with.

I will expect to get going in few days.

**Comment by kum-deepak** [comment]
Hi @fpozzobon, I have created a task which will be used for general discussions. Please join at https://github.com/stomp-js/stompjs/issues/1
